server:
  port: 8888
spring:
  application:
    name: zuul-server
  ##redis共享session
  redis:
    host: 10.1.13.74
    port: 6379
    ## 连接池中的最大连接数
    poolMaxTotal: 10
    ## 连接池中的最大空闲连接
    poolMaxIdle:
    ##使用0号数据库
    database: 0

#连接注册中心的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8050/eureka/

zuul:
  sensitive-headers: "*"
  routes:
    mybank-server: /mybank/**
    domestic-server: /domestic/**
    manage-server: /manage/**
  host:
    connect-timeout-millis: 10000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 50000   #socket超时
#  ratelimit:
#    key-prefix: goods_ratelimit #按粒度拆分的临时变量key前缀
#    enabled: true #启用开关
#    repository: REDIS#key存储，默认是IN_MEMORY本地内存，此外还有多种形式
#    behind-proxy: true #表示代理之后
#    default-policy: #全局限流策略，可单独细化到服务粒度
#      limit: 20 #在一个单位时间窗口的请求数量
#      quota: 60 #在一个单位时间窗口的请求时间总耗时限制
#      refresh-interval: 3 #单位时间窗口
#      type: url  #可指定url粒度
  #每个请求在3秒内不能超过2次请求,并且总时间不能超过6秒
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
#熔断器超时
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000