#客户端端口
server:
  port: 8060

#连接注册中心的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8050/eureka/

#集成oracle
spring:
  #该服务在注册中心的名称
  application:
    name: mybank-server
  datasource:
    username: java38
    password: 123456
    url: jdbc:oracle:thin:@10.1.13.44:1521:orcl
#    url: jdbc:oracle:thin:@47.100.61.199:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
  #关于freemarker配置
  freemarker:
    #关闭缓存
    cache: false
    #数值不采取三分法
    settings:
      number_format: 0.##
      classic_compatible: true
    suffix: .html
  rabbitmq:
    port: 5672
    host: 10.1.13.74
#    host: localhost
    username: admin
    password: 123456
    listener:
      simple:
        #设置消费端手动 ack
        acknowledge-mode: manual
        #消费者最小数量
        concurrency: 1
        #消费之最大数量
        max-concurrency: 20
        #在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
        prefetch: 1
#  redis:
#    host: 10.1.13.74
##    host: localhost
#    port: 6379
#    ## 连接池中的最大连接数
#    poolMaxTotal: 10
#    ## 连接池中的最大空闲连接
#    poolMaxIdle: 10
#    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#    database: 0

#集成mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zl.pojo
  configuration:
    jdbc-type-for-null: varchar



